_target_: source.model.RawNet

sinc_out_channels: 20
sinc_kernel_size: 1024

ResBlocks: [[20, 20], [20, 20], [20, 128], [128, 128], [128, 128], [128, 128]]

gru_input_size: 128
gru_hidden_size: 1024
gru_num_layers: 3
